name: Build release

on: 
  release:
    types: [created]
    
jobs:      
  build:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Update apt and install dependencies
        run: |
          sudo apt-get update
          # deps for yocto build
          sudo apt-get -y install apt-utils gawk wget git diffstat unzip texinfo gcc build-essential chrpath socat cpio python3 python3-pip python3-pexpect xz-utils debianutils iputils-ping python3-git python3-jinja2 libegl1-mesa libsdl1.2-dev pylint3 xterm python3-subunit mesa-common-dev zstd liblz4-tool
          # deps for menuconfig commands
          sudo apt-get -y install tmux libncurses-dev bison flex sudo

      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'hestiia-engineering/yocto-cooker-myeko'
          file: 'poky-glibc-x86_64-myeko-image-dev-cortexa8hf-neon-myeko-board-toolchain-4.0.12.sh '
          target: 'sdk.sh'
          token: ${{ secrets.GIT_TOKEN }}
      - name: Extract Yocto SDK
        run: |
            chmod +x sdk.sh
            ./sdk.sh -d ./sdk -y -D
      - name: Source Yocto SDK Environment
        run: |
          source sdk/environment-setup-cortexa8hf-neon-poky-linux-gnueabi
          
      - name: Build the project
        run: |
          source ./sdk/environment-setup-cortexa8hf-neon-poky-linux-gnueabi
          ./update_configure_ac_version.sh
          mkdir -p ./build_yocto && cd build_yocto
          ../autogen.sh
          CFLAGS="-O2 -Wall -fcommon" ../configure ${CONFIGURE_FLAGS} --enable-bm1397
          make
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          # Artifact name
          name: cgminer
          # A file, directory or wildcard pattern that describes what to upload
          path: ./build_yocto/cgminer
          # The desired behavior if no files are found using the provided path.    
          if-no-files-found: error
          
      - name: Upload all build artifacts as release files
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          RELEASE_TAG=$GITHUB_REF_NAME
          # Upload artifacts, potentially overwriting existing files (--clobber)
          gh release upload $RELEASE_TAG ./build_yocto/cgminer#cgminer_$RELEASE_TAG_armv7_yocto --clobber
